# Generated by Django 5.2.3 on 2025-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginrecord",
            name="campo_teste",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
