# Generated by Django 5.2.3 on 2025-06-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_record", "0002_alter_loginrecord_campo_teste"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginrecord",
            options={"verbose_name": "Registro de Login", "verbose_name_plural": "Registros de Login"},
        ),
    ]
