services:
  ollama:
    image: ollama/ollama:latest
    container_name: base_tests_ollama_gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init-ollama.sh:/init-ollama.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MAX_QUEUE=512
    restart: unless-stopped
    entrypoint: ["/init-ollama.sh"]
    # Configurações para GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16G
        reservations:
          memory: 8G
    # Otimizações de performance
    shm_size: 4gb
    ulimits:
      memlock: -1
      stack: 67108864

volumes:
  ollama_data:
