services:
  ollama:
    image: ollama/ollama:latest
    container_name: base_tests_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init-ollama.sh:/init-ollama.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    entrypoint: ["/init-ollama.sh"]

volumes:
  ollama_data:
