# Generated by Django 5.2 on 2025-04-29 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "field_changed",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Changed field",
                    ),
                ),
                (
                    "field_changed_display",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Changed field display",
                    ),
                ),
                (
                    "current_value",
                    models.TextField(
                        editable=False,
                        max_length=4000,
                        null=True,
                        verbose_name="Current value",
                    ),
                ),
                (
                    "previous_value",
                    models.TextField(
                        editable=False,
                        max_length=4000,
                        null=True,
                        verbose_name="Previous value",
                    ),
                ),
                ("object_id", models.UUIDField(editable=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
