# Generated by Django 5.2.3 on 2025-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abstract", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updateuser",
            name="current_value",
            field=models.TextField(
                blank=True, default="", editable=False, max_length=4000, verbose_name="Current value"
            ),
        ),
        migrations.AlterField(
            model_name="updateuser",
            name="field_changed",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100, verbose_name="Changed field"
            ),
        ),
        migrations.AlterField(
            model_name="updateuser",
            name="field_changed_display",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=100, verbose_name="Changed field display"
            ),
        ),
        migrations.AlterField(
            model_name="updateuser",
            name="previous_value",
            field=models.TextField(
                blank=True, default="", editable=False, max_length=4000, verbose_name="Previous value"
            ),
        ),
    ]
