# Generated by Django 5.2.3 on 2025-06-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abstract", "0003_alter_updateuser_current_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="updateuser",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Registro de Alteração",
                "verbose_name_plural": "Registros de Alteração",
            },
        ),
    ]
