# Generated by Django 5.2 on 2025-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_clb_perm",
            field=models.BooleanField(default=False, verbose_name="Has CLB permission"),
        ),
        migrations.AddField(
            model_name="user",
            name="has_rh_perm",
            field=models.BooleanField(default=False, verbose_name="HAS RH permission"),
        ),
    ]
