# Generated by Django 5.2 on 2025-05-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0003_alter_user_create_user_alter_user_update_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="users", verbose_name="Image"),
        ),
    ]
