# Generated by Django 5.2 on 2025-05-27 12:01

from django.db import migrations, models

import drf_base_apps.core.drf_base_user.models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0004_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_changed_password",
            field=models.BooleanField(default=False, editable=False, verbose_name="Has Changed Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=drf_base_apps.core.drf_base_user.models.user_image_path,
                verbose_name="Image",
            ),
        ),
    ]
