# Generated by Django 5.2.3 on 2025-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0005_user_has_changed_password_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, default="", max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="user",
            name="login_date",
            field=models.DateField(blank=True, editable=False, null=True, verbose_name="Login today"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.TextField(blank=True, default="", verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="rg",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="RG"),
        ),
    ]
