# Generated by Django 5.2.3 on 2025-07-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0006_alter_user_cpf_alter_user_login_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_clb_perm",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_rh_perm",
        ),
    ]
