# Generated by Django 5.2.4 on 2025-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0007_remove_user_has_clb_perm_remove_user_has_rh_perm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("A", "Ativo"), ("I", "Inativo"), ("P", "Pendente"), ("R", "Rejeitado")],
                default="P",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
