# Generated by Django 5.2.4 on 2025-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_base_user", "0008_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(null=True, max_length=254, verbose_name="email address"),
        ),
    ]
